reprocudible: mke2img uses SOURCE_DATE_EPOCH (incomplete)

diff --git a/tools/mke2img b/tools/mke2img
--- a/tools/mke2img
+++ b/tools/mke2img
@@ -151,6 +151,27 @@ main() {
     trace "e2fsck was successfully run on '%s' (ext%d)\n" "${image}" ${gen}
     printf "\n"
 
+    # set a reproducible uuid and last-check date
+    if [ -n "$SOURCE_DATE_EPOCH" ]; then
+        local UUID=''
+        if   [ -x "$TOOLS/python2" ]; then
+             UUID="$($TOOLS/python2 -c "import uuid; print(uuid.uuid3(uuid.NAMESPACE_URL,'freetz-$SOURCE_DATE_EPOCH'))")"
+        elif [ -x "$TOOLS/python3" ]; then
+             UUID="$($TOOLS/python3 -c "import uuid; print(uuid.uuid3(uuid.NAMESPACE_URL,'freetz-$SOURCE_DATE_EPOCH'))")"
+        elif command -v python3 >/dev/null; then
+             UUID="$(python3 -c "import uuid; print(uuid.uuid3(uuid.NAMESPACE_URL,'freetz-$SOURCE_DATE_EPOCH'))")"
+        elif command -v python2 >/dev/null; then
+             UUID="$(python2 -c "import uuid; print(uuid.uuid3(uuid.NAMESPACE_URL,'freetz-$SOURCE_DATE_EPOCH'))")"
+        elif command -v uuidgen >/dev/null; then
+             UUID="$($TOOLS/uuidgen --sha1 --namespace @dns --name "freetz-$SOURCE_DATE_EPOCH")"
+        fi
+        [ -z "$UUID" ] && echo "Failed, python2(-host), python3(-host) or uuidgen is required to generate the UUID." && exit 1
+        $TOOLS/tune2fs \
+          -U "$UUID" \
+          -T "$(date -d@"$SOURCE_DATE_EPOCH" "+%Y%m%d%H%M%S")" \
+          "${image}"
+    fi
+
     # Remove count- and time-based checks, they are not welcome
     # on embedded devices, where they can cause serious boot-time
     # issues by tremendously slowing down the boot.
@@ -167,6 +188,9 @@ SYNOPSIS
 
 DESCRIPTION
     Create ext2/3/4 filesystem image from the content of a directory.
+
+    reproducible (incomplete):
+      If SOURCE_DATE_EPOCH is set it overwrites the UUID and the last-check time.
 
     -b BLOCKS
         Create a filesystem of BLOCKS 1024-byte blocs. The default is to
