prereq: support latest bs versions

diff --git a/tools/prerequisites b/tools/prerequisites
--- a/tools/prerequisites
+++ b/tools/prerequisites
@@ -102,12 +102,16 @@ install_requisite() {
 	[ -z "$OSV" ] && OSV="$(detect_linux)"
 	[ -z "$OSV" ] && echo 'Can not detect you Linux version, set it manually'&& list_linux  && exit 1
 
-	[ ! -e "$PACKAGES/${OSV##*/}" ] && echo "Unsupported, file for your Linux version not found: ${OSV##*/}" && list_linux && exit 1
+	OSV="${OSV##*/}"
+	GENERIC="$(echo "$OSV" | sed 's/[0-9]*$//')"
+	[ ! -e "$PACKAGES/$OSV" ] && [ -e "$PACKAGES/$GENERIC" ] && OSV="$GENERIC"
 
-	vals="$(sed 's/[\t ]*#.*//g' "$PACKAGES/${OSV##*/}" | sort | tr '\n' ' ' | sed 's/^ *//;s/  */ /g;s/ *$//')"
-	echo -e "\nPackages for '${OSV##*/}':\n$vals\n"
+	[ ! -e "$PACKAGES/$OSV" ] && echo "Unsupported, file for your Linux version not found: $OSV" && list_linux && exit 1
+
+	vals="$(sed 's/[\t ]*#.*//g' "$PACKAGES/$OSV" | sort | tr '\n' ' ' | sed 's/^ *//;s/  */ /g;s/ *$//')"
+	echo -e "\nPackages for '$OSV':\n$vals\n"
 	[ "${ARG:0:1}" == "s" ] && exit 0
-	case "${OSV##*/}" in
+	case "$OSV" in
 		Fedora*)                               sudo dnf --refresh  install $DOY $vals || exit 1 ;;
 		Debian*)        sudo apt-get update && sudo apt            install $DOY $vals || exit 1 ;;
 		Ubuntu*|Mint*)  sudo apt-get update && sudo apt-get        install $DOY $vals || exit 1 ;;
